### ISSUE TITLE
情感字典舆情统计问题

### ISSUE THREAD

**Issue by zhanghuicuc** [Linlidi/StockSensation#2]
感谢作者~
请问，为什么积极情绪+中立情绪+消极情绪的总数不等于发帖总数？

**Comment by LinLidi** [comment]
Hi @zhanghuicuc ：
感谢关注，因为版本比较旧，逻辑有些简单，【积极情绪+中立情绪+消极情绪的总数不等于发帖总数】因为有些帖子中没有这三种任一情绪词汇。
祝好！
